require: 
  - rubocop-rails

Rails:
  Enabled: true
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.2
  Exclude:
    # Generated files
    - config/puma.rb
    - config.ru
    - bin/**/*
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/*
    - lib/tasks/default.rake
    - lib/tasks/cucumber.rake

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false